print("This is a print statement")
print("What's wrong with this statement?")
print("How about this one?")
print ("hello")
print ("dylan is dating an '06")
print (5)
print (3.14)
print ("Here are the ages of my three children:",12 ,7 ,4)
print ("his pants are", colour)